name: Terraform-Plan
on:
  push:
    - main
  pull_request:

env:
  GCP_PROJECT: corporacion-sales-prediction
  GCP_region: europe-west1

jobs:
  detect-changes:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - id: changes
    - uses: dorny/paths-filter@v3
      with: |
        filters: |
          infra:
            - 'terraform/**'
  
  tf-plan:
    needs: detect-changes
    if: needs.detec-changes.outputs.infra == 'true'
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Authentication to google cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEY_JSON }}
        
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        env:
          project_id: ${{ env.GCP_PROJECT }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2
      
      - name: Terraform fmt
        working-directory: terraform
        run: terraform fmt -check -recursive
      
      - name: Terraform init
        working-directory: terraform
        run: terraform init -input=false
      
      - name: Terraform validate
        working-directory: terraform
        run: terraform validate -no-color
      