name: Terraform-apply
on:
  # workflow_run:
  #   workflows: ["Terraform-Plan"]
  #   type: ["completed"]
  workflow_dispatch:
    inputs:
      sha:
        description: "commit sha to apply"
        required: true
        type: string
      run_id:
        description: "workflow run_id from CI"
        required: true

permissions:
  actions: read
  contents: read

concurrency:
  group: tf-apply-${{ github.repository }}
  cancel-in-progress: true

env:
  GCP_PROJECT: corporacion-sales-forecasting
  GCP_REGION: europe-west1
  TF_VERSION: 1.9.2
  GCP_UMSA: corpor-sales-sa

jobs:
  terraform-apply:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Get target commit sha
        id: commit_sha
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.sha }}" ];then
            echo "${{ github.event.inputs.sha }}"
            echo "sha=${{ github.event.inputs.sha }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "workflow_run" ];then
            echo "sha=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT
          else
            echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.commit_sha.outputs.sha }}
      
      - name: Authenticate to google gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEY_JSON }}
      
      - name: Setup google gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}
      
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Install packages for downloading data
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends unzip p7zip-full python3-pip
          python3 -m pip install --user kaggle
          echo '$HOME/.local/bin' >> '$GITHUB_PATH'
      
      - name: Write kaggle credentials
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          printf '{"username":"%s","key":"%s"}' "$KAGGLE_USERNAME" "$KAGGLE_KEY" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
      
      - name: Download competition data
        run: |
          chmod +x shell_scripts/data_download.sh
          shell_scripts/data_download.sh
      
      - name: Download tf-plan artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: Terraform-Plan
          run_id: ${{ github.event.inputs.run_id }}
          name: tfplan-${{ steps.commit_sha.outputs.sha }}
          path: terraform
      
      - name: Verify plan file presence
        run: |
          test -f terraform/tfplan.bin || { echo 'tfplan.bin file does not exist in terraform/ folder'; exit 1; }
      
      - name: Terraform init to obtain the backend
        working-directory: terraform
        run: terraform init -input=false
      
      - name: Terraform apply
        working-directory: terraform
        env:
          TF_VAR_project_id: ${{ env.GCP_PROJECT }}
          TF_VAR_region: ${{ env.GCP_REGION }}
          TF_VAR_UMSA: ${{ env.GCP_UMSA }}
        run: terraform apply -input=false --auto-approve tfplan.bin
      
      